"""HTTP response models and shared OpenAPI description constants."""

from models.api.responses.constants import (
    BAD_REQUEST_DESCRIPTION,
    CONFLICT_DESCRIPTION,
    FILE_UPLOAD_EXCEEDS_SIZE_LIMIT_DESCRIPTION,
    FORBIDDEN_DESCRIPTION,
    INTERNAL_SERVER_ERROR_DESCRIPTION,
    INVALID_FEEDBACK_PATH_DESCRIPTION,
    NOT_FOUND_DESCRIPTION,
    PROMPT_TOO_LONG_DESCRIPTION,
    QUOTA_EXCEEDED_DESCRIPTION,
    SERVICE_UNAVAILABLE_DESCRIPTION,
    SUCCESSFUL_RESPONSE_DESCRIPTION,
    UNAUTHORIZED_DESCRIPTION,
    UNAUTHORIZED_OPENAPI_EXAMPLES,
    UNAUTHORIZED_OPENAPI_EXAMPLES_WITH_MCP_OAUTH,
    UNPROCESSABLE_CONTENT_DESCRIPTION,
)
from models.api.responses.error import (
    AbstractErrorResponse,
    BadRequestResponse,
    ConflictResponse,
    DetailModel,
    FileTooLargeResponse,
    ForbiddenResponse,
    InternalServerErrorResponse,
    NotFoundResponse,
    PromptTooLongResponse,
    QuotaExceededResponse,
    ServiceUnavailableResponse,
    UnauthorizedResponse,
    UnprocessableEntityResponse,
)

__all__ = [
    "BAD_REQUEST_DESCRIPTION",
    "CONFLICT_DESCRIPTION",
    "FILE_UPLOAD_EXCEEDS_SIZE_LIMIT_DESCRIPTION",
    "FORBIDDEN_DESCRIPTION",
    "INTERNAL_SERVER_ERROR_DESCRIPTION",
    "INVALID_FEEDBACK_PATH_DESCRIPTION",
    "NOT_FOUND_DESCRIPTION",
    "PROMPT_TOO_LONG_DESCRIPTION",
    "QUOTA_EXCEEDED_DESCRIPTION",
    "SERVICE_UNAVAILABLE_DESCRIPTION",
    "SUCCESSFUL_RESPONSE_DESCRIPTION",
    "UNAUTHORIZED_DESCRIPTION",
    "UNAUTHORIZED_OPENAPI_EXAMPLES",
    "UNAUTHORIZED_OPENAPI_EXAMPLES_WITH_MCP_OAUTH",
    "UNPROCESSABLE_CONTENT_DESCRIPTION",
    "AbstractErrorResponse",
    "BadRequestResponse",
    "ConflictResponse",
    "DetailModel",
    "ForbiddenResponse",
    "InternalServerErrorResponse",
    "NotFoundResponse",
    "PromptTooLongResponse",
    "FileTooLargeResponse",
    "QuotaExceededResponse",
    "ServiceUnavailableResponse",
    "UnauthorizedResponse",
    "UnprocessableEntityResponse",
]
