#!/bin/bash

# Script to split requirements by index source
# Packages from pypi.org go to requirements.source.txt
# Packages from console.redhat.com go to requirements.wheel.txt

RAW_REQ_FILE="requirements.no_hashes.txt"
SOURCE_FILE="requirements.source.txt"
WHEEL_FILE="requirements.wheel.txt"
SOURCE_HASH_FILE="requirements.hashes.source.txt"
WHEEL_HASH_FILE="requirements.hashes.wheel.txt"
BUILD_FILE="requirements-build.txt"

# extra wheels to be included in the wheel list, often come from build-time dependencies
EXTRA_WHEELS="uv,pip,maturin"
# packages to exclude from the wheel list
NO_WHEEL_PACKAGES="markupsafe"

# Generate requirements list from pyproject.toml from both indexes
uv pip compile pyproject.toml -o "$RAW_REQ_FILE" \
		--group llslibdev \
		--python-platform x86_64-unknown-linux-gnu \
		--python-version 3.12 \
		--refresh \
		--index https://console.redhat.com/api/pypi/public-rhai/rhoai/3.2/cpu-ubi9/simple/ \
		--default-index https://pypi.org/simple/ \
		--index-strategy unsafe-best-match \
		--emit-index-annotation \
		--no-sources \
		--override requirements.overrides.txt

# Initialize output files
echo "# Packages from pypi.org" > "$SOURCE_FILE"
echo "# This file was autogenerated by split_requirements.sh" >> "$SOURCE_FILE"
echo "# Packages from console.redhat.com" > "$WHEEL_FILE"
echo "# This file was autogenerated by split_requirements.sh" >> "$WHEEL_FILE"
echo "--index-url https://console.redhat.com/api/pypi/public-rhai/rhoai/3.2/cpu-ubi9/simple/" >> "$WHEEL_FILE"

current_package=""

while IFS= read -r line || [[ -n "$line" ]]; do
    # Check if this is a package line (starts with a letter/digit, not whitespace or #)
    if [[ "$line" =~ ^[a-zA-Z0-9] ]]; then
        current_package="$line"
        package_name="${current_package%%==*}"
    # Check if this is a "# from" annotation line
    elif [[ "$line" =~ ^[[:space:]]*#[[:space:]]*from[[:space:]]+(.*) ]]; then
        index_url="${BASH_REMATCH[1]}"

        if [[ -n "$current_package" ]]; then
            if [[ "$index_url" == "https://pypi.org/simple/" ]]; then
                echo "$current_package" >> "$SOURCE_FILE"
            elif [[ "$NO_WHEEL_PACKAGES" == *"$package_name"* ]]; then
                echo "$current_package" >> "$SOURCE_FILE"
            elif [[ "$index_url" == "https://console.redhat.com/api/pypi/public-rhai/rhoai/3.2/cpu-ubi9/simple/" ]]; then
                echo "$current_package" >> "$WHEEL_FILE"
            fi
            current_package=""
        fi
    fi
done < "$RAW_REQ_FILE"

# replace the list of binary packages in konflux pipeline configuration
# only the package names, not the versions, delimited by commas
wheel_packages=$(grep -v "^[#-]" "$WHEEL_FILE" | sed 's/==.*//' | tr '\n' ',' | sed 's/,$//')
# append extra wheels to the list
wheel_packages="$wheel_packages,$EXTRA_WHEELS"
sed -i 's/"packages": "[^"]*"/"packages": "'"$wheel_packages"'"/' .tekton/lightspeed-stack-pull-request.yaml
sed -i 's/"packages": "[^"]*"/"packages": "'"$wheel_packages"'"/' .tekton/lightspeed-stack-push.yaml

echo "Packages from pypi.org written to: $SOURCE_FILE ($(wc -l < "$SOURCE_FILE") packages)"
echo "Packages from console.redhat.com written to: $WHEEL_FILE ($(wc -l < "$WHEEL_FILE") packages)"


uv pip compile "$WHEEL_FILE" --refresh --generate-hashes --index-url https://console.redhat.com/api/pypi/public-rhai/rhoai/3.2/cpu-ubi9/simple/ --python-version 3.12 --emit-index-url --no-deps --no-annotate --universal >  "$WHEEL_HASH_FILE"
uv pip compile "$SOURCE_FILE" --refresh --generate-hashes --python-version 3.12 --emit-index-url --no-deps --no-annotate > "$SOURCE_HASH_FILE"
uv run pybuild-deps compile --output-file="$BUILD_FILE" "$SOURCE_FILE"

# pin maturin to the version available in the Red Hat registry
sed -i 's/maturin==[0-9.]*/maturin==1.10.2/' "$BUILD_FILE"

# remove intermediate files
rm "$RAW_REQ_FILE" "$WHEEL_FILE" "$SOURCE_FILE"

echo "Done!"
echo "Packages from pypi.org written to: $SOURCE_HASH_FILE ($(wc -l < "$SOURCE_HASH_FILE") packages)"
echo "Packages from console.redhat.com written to: $WHEEL_HASH_FILE ($(wc -l < "$WHEEL_HASH_FILE") packages)"
echo "Build dependencies written to: $BUILD_FILE ($(wc -l < "$BUILD_FILE") packages)"
echo "Remember to commit $SOURCE_HASH_FILE, $WHEEL_HASH_FILE, $BUILD_FILE, pipeline configurations and push the changes"